### ISSUE TITLE
EOD2-SME discussion

### ISSUE THREAD

**Issue by BennyThadikaran** [BennyThadikaran/eod2-sme#1]
#https://github.com/BennyThadikaran/eod2/issues/31

Opened to discuss features related to SME inclusion in EOD2

**Comment by BennyThadikaran** [comment]
Here is some information i have about SME stocks. 

There are 2 series: SM and ST. This has something to do with rolling settlement or trade to trade settlement. All we need to ensure is filter both these segments in the bhavcopy.

There no restrictions on bonus and splits. See corporate actions of [Goldstar Power Limited](https://www.nseindia.com/get-quotes/equity?symbol=GOLDSTAR)

I will need to test if the regex works correctly to detect the bonus and splits.

**Comment by BennyThadikaran** [comment]
I have added some working code to the repo. Its mostly code from EOD2 slightly modified for SME stocks.

Next i will need to
1. Parse the bhavcopies for historic sme data.
2. Download the corporate actions for each of the stocks and parse it for bonus and splits.

The scripts are mostly ready but will need to be modified for SME stocks.

**Comment by cotton1234** [comment]
Thanks Benny

**Comment by BennyThadikaran** [comment]
@cotton1234 I have just completed pushing some major updates to eod2. I think you might like the latest changes. See the wiki for updated documentation.

I am now free to work on this code. Will get cracking on Monday. 

Please star EOD2, if you like the work so far.

**Comment by cotton1234** [comment]
Thanks Benny. All my daily analysis is with EOD2 data only. Will get the new update and check.
I start the EOD code. 

Regards
Saurabh

**Comment by BennyThadikaran** [comment]
I have extracted all the SME stocks from 2nd Nov 2012 to current date. In all i got 353 files. Many of them are no longer active. 

I also got all the corporate actions for these companies. Earliest recorded corporate action was 28th Aug 2015.

I will adjust the stocks tomorrow. Hopefully its all straight forward.

**Comment by cotton1234** [comment]
> 

SME stocks are listed when they come out with fresh IPO and since they are small and medium enterprise they trade in lots. But as the capital grow of the company. then they take decision to trade in EQ category.

You should not let it continue as SME if its moved to EQ category as they will start trading there and we will get the data from there.

Waiting for the push, so can try out the SME.

Thanks
Saurabh

**Comment by BennyThadikaran** [comment]
Ok everything is done. Just run `git pull` followed by `git submodule update --init`

Let me know if everything went smoothly.

**Comment by BennyThadikaran** [comment]
> > 
> 
> SME stocks are listed when they come out with fresh IPO and since they are small and medium enterprise they trade in lots. But as the capital grow of the company. then they take decision to trade in EQ category.
> 
> You should not let it continue as SME if its moved to EQ category as they will start trading there and we will get the data from there.
> 
> Waiting for the push, so can try out the SME.
> 
> Thanks Saurabh

Its a good thing i kept the repo separate else the potential to overwrite the existing stock files without my knowledge. BTW i there was not a single bonus or split adjustment required in any of the files. Either the NSE rules don't permit or SME companies rarely opt for it.

I never knew about SME. Now learnt a lot thanks to you. :+1:

**Comment by cotton1234** [comment]
> Ok everything is done. Just run `git pull` followed by `git submodule update --init`
> 
> Let me know if everything went smoothly.

Thank you so much Benny. Just pulled the repo. Will be checking for data issue if any and let you know.
Now need to modify my code so it can give signals for trading.

Thanks
Saurabh

**Comment by cotton1234** [comment]
> > > 
> > 
> > 
> > SME stocks are listed when they come out with fresh IPO and since they are small and medium enterprise they trade in lots. But as the capital grow of the company. then they take decision to trade in EQ category.
> > You should not let it continue as SME if its moved to EQ category as they will start trading there and we will get the data from there.
> > Waiting for the push, so can try out the SME.
> > Thanks Saurabh
> 
> Its a good thing i kept the repo separate else the potential to overwrite the existing stock files without my knowledge. BTW there was not a single bonus or split adjustment required in any of the files. Either the NSE rules don't permit or SME companies rarely opt for it.
> 
> I never knew about SME. Now learnt a lot thanks to you. 👍

You Welcome Benny !!

**Comment by cotton1234** [comment]
Can we rename the file in the format <Stock_name>_SME.csv
This way it will be easier to merge it in into eod2 repo and still distinguish the SME stocks.

Thanks
Saurabh

**Comment by BennyThadikaran** [comment]
You want the SME and regular stocks together in the `eod2_data/daily` folder? Is there a specific reason you want it that way.

There are only 200 files so adding it wont be a big issue. I prefer keep them separate for neatness sake. It also easier to plug and delete if not necessary. 

What you're suggesting also has its merits. It can become a permanent for all, without an opt in feature. Less code and less complications.

Let me think over it.

**Comment by cotton1234** [comment]
You can put this same way you have included ambiroker thing. True and false and based on the input mark the files with "_sme" as any other member using this SME stocks would like to have all the csv in 1 folder as its becomes easy to process for analysis.
Thanks

**Comment by BennyThadikaran** [comment]
I think your suggestion is better. All SME files will be added to `eod2_data` with `_sme` as the end. No options. This is the easier path, less code and no complications.

Adding a submodule folder will require tracking the lastupdate of both the folders separately. (SME data could be a week old depending on when the user downloads it). All that effort for 250 extra files is not worth it.

I will add some if conditions in `plot.py` and `dget.py` to check for `_sme` if a regular file is not found. That way user is not required to explicitly add `_sme` just to plot a chart etc.

I'm traveling next week so will merge this repo with EOD2 after 7th Sept.

**Comment by cotton1234** [comment]
> 

Yes don't add submodule .
When the user updates EOD2, SME based stocks will also get updated and it will be current for the user.

Take your time , and enjoy your travel.

Thanks
Saurabh

**Comment by BennyThadikaran** [comment]
@cotton1234 

Hi Saurabh,

I have merged SME stocks into EOD2. All SME stocks have a prefix `_sme`. I performed a sync yesterday without any problems.

To sync your local repo. go to the `src/eod2_data` folder. If running `git status` shows detached head,  run `git checkout main`

In the `src/eod2_data` folder, run `git pull`. This will pull all changes upto 7th Sep 2023.

Next from the project root folder, run `git pull`. This will pull all changes in the eod2 repo.

**Don't sync the data, until you've done the above, to avoid dealing with git conflicts.**

Let me know if everything ran smoothly.

**Comment by cotton1234** [comment]
Hello Benny,

I am traveling and out of city. Will sync by weekend and update.

Thanks
Saurabh

**Comment by BennyThadikaran** [comment]
No worries. Enjoy your travel!

**Comment by cotton1234** [comment]
Hello Benny,

I have pulled whole eod2 folder just now instead of the commands which you asked me.

Will check and get back if i find more issues.

Thanks
Saurabh

**Comment by BennyThadikaran** [comment]
I guess the work here is done. I'll close this issue now and delete the repo tomorrow evening. Any issues regards SME stocks can be directly raised in EOD2 repo.

**Comment by cotton1234** [comment]
Thank you So much Benny!!
